{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"machine_shape":"hm"},"kernelspec":{"name":"python3","display_name":"Python 3"},"accelerator":"GPU"},"cells":[{"cell_type":"markdown","source":["![Memories Teach](https://lh3.google.com/u/2/d/11o4JyBYhHcmz-LSt63GpOs4lfW9j39T_=w1912-h954-iv1)\n","\n","\n","`Basic to Advance in Google colab's for image processing, pattern recognition and computer vision`\n","\n","[Phonepaserth SISAYKEO]\n","\n","Reference: visioncolab"],"metadata":{"id":"Vs6wiDWXs-X0"}},{"cell_type":"markdown","metadata":{"id":"Jt2lQLa9MucL"},"source":["# Face Age & Gender\n","\n","\n"]},{"cell_type":"markdown","metadata":{"id":"dJBiMoMrRTXq"},"source":["## Library loading\n","\n","*The py-agender library works with tensorflow 1.15.5*."]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/","height":1000},"id":"a-JxM2wLT96t","outputId":"c58f3b8b-f301-401e-f409-9151c79d0ab4"},"source":["!pip install --force-reinstall tensorflow==1.15.5"],"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/\n","Collecting tensorflow==1.15.5\n","  Downloading tensorflow-1.15.5-cp37-cp37m-manylinux2010_x86_64.whl (110.5 MB)\n","\u001b[K     |████████████████████████████████| 110.5 MB 1.9 kB/s \n","\u001b[?25hCollecting numpy<1.19.0,>=1.16.0\n","  Downloading numpy-1.18.5-cp37-cp37m-manylinux1_x86_64.whl (20.1 MB)\n","\u001b[K     |████████████████████████████████| 20.1 MB 59.1 MB/s \n","\u001b[?25hCollecting tensorflow-estimator==1.15.1\n","  Downloading tensorflow_estimator-1.15.1-py2.py3-none-any.whl (503 kB)\n","\u001b[K     |████████████████████████████████| 503 kB 51.3 MB/s \n","\u001b[?25hCollecting google-pasta>=0.1.6\n","  Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)\n","\u001b[K     |████████████████████████████████| 57 kB 5.8 MB/s \n","\u001b[?25hCollecting protobuf>=3.6.1\n","  Downloading protobuf-4.21.7-cp37-abi3-manylinux2014_x86_64.whl (408 kB)\n","\u001b[K     |████████████████████████████████| 408 kB 59.3 MB/s \n","\u001b[?25hCollecting h5py<=2.10.0\n","  Downloading h5py-2.10.0-cp37-cp37m-manylinux1_x86_64.whl (2.9 MB)\n","\u001b[K     |████████████████████████████████| 2.9 MB 55.7 MB/s \n","\u001b[?25hCollecting grpcio>=1.8.6\n","  Downloading grpcio-1.49.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.7 MB)\n","\u001b[K     |████████████████████████████████| 4.7 MB 52.7 MB/s \n","\u001b[?25hCollecting wheel>=0.26\n","  Downloading wheel-0.37.1-py2.py3-none-any.whl (35 kB)\n","Collecting wrapt>=1.11.1\n","  Downloading wrapt-1.14.1-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (75 kB)\n","\u001b[K     |████████████████████████████████| 75 kB 4.8 MB/s \n","\u001b[?25hCollecting keras-preprocessing>=1.0.5\n","  Downloading Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)\n","\u001b[K     |████████████████████████████████| 42 kB 1.5 MB/s \n","\u001b[?25hCollecting gast==0.2.2\n","  Downloading gast-0.2.2.tar.gz (10 kB)\n","Collecting six>=1.10.0\n","  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)\n","Collecting tensorboard<1.16.0,>=1.15.0\n","  Downloading tensorboard-1.15.0-py3-none-any.whl (3.8 MB)\n","\u001b[K     |████████████████████████████████| 3.8 MB 59.7 MB/s \n","\u001b[?25hCollecting absl-py>=0.7.0\n","  Downloading absl_py-1.2.0-py3-none-any.whl (123 kB)\n","\u001b[K     |████████████████████████████████| 123 kB 79.4 MB/s \n","\u001b[?25hCollecting termcolor>=1.1.0\n","  Downloading termcolor-2.0.1-py3-none-any.whl (5.4 kB)\n","Collecting keras-applications>=1.0.8\n","  Downloading Keras_Applications-1.0.8-py3-none-any.whl (50 kB)\n","\u001b[K     |████████████████████████████████| 50 kB 7.8 MB/s \n","\u001b[?25hCollecting opt-einsum>=2.3.2\n","  Downloading opt_einsum-3.3.0-py3-none-any.whl (65 kB)\n","\u001b[K     |████████████████████████████████| 65 kB 4.7 MB/s \n","\u001b[?25hCollecting astor>=0.6.0\n","  Downloading astor-0.8.1-py2.py3-none-any.whl (27 kB)\n","Collecting markdown>=2.6.8\n","  Downloading Markdown-3.4.1-py3-none-any.whl (93 kB)\n","\u001b[K     |████████████████████████████████| 93 kB 1.8 MB/s \n","\u001b[?25hCollecting setuptools>=41.0.0\n","  Downloading setuptools-65.4.1-py3-none-any.whl (1.2 MB)\n","\u001b[K     |████████████████████████████████| 1.2 MB 55.8 MB/s \n","\u001b[?25hCollecting werkzeug>=0.11.15\n","  Downloading Werkzeug-2.2.2-py3-none-any.whl (232 kB)\n","\u001b[K     |████████████████████████████████| 232 kB 65.3 MB/s \n","\u001b[?25hCollecting importlib-metadata>=4.4\n","  Downloading importlib_metadata-5.0.0-py3-none-any.whl (21 kB)\n","Collecting typing-extensions>=3.6.4\n","  Downloading typing_extensions-4.4.0-py3-none-any.whl (26 kB)\n","Collecting zipp>=0.5\n","  Downloading zipp-3.9.0-py3-none-any.whl (5.8 kB)\n","Collecting MarkupSafe>=2.1.1\n","  Downloading MarkupSafe-2.1.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)\n","Building wheels for collected packages: gast\n","  Building wheel for gast (setup.py) ... \u001b[?25l\u001b[?25hdone\n","  Created wheel for gast: filename=gast-0.2.2-py3-none-any.whl size=7554 sha256=3e724c2765f6ea2ea66a2ce2f851fa25c45494196aec7a333a88dcaa0abf9e0a\n","  Stored in directory: /root/.cache/pip/wheels/21/7f/02/420f32a803f7d0967b48dd823da3f558c5166991bfd204eef3\n","Successfully built gast\n","Installing collected packages: zipp, typing-extensions, six, numpy, MarkupSafe, importlib-metadata, wheel, werkzeug, setuptools, protobuf, markdown, h5py, grpcio, absl-py, wrapt, termcolor, tensorflow-estimator, tensorboard, opt-einsum, keras-preprocessing, keras-applications, google-pasta, gast, astor, tensorflow\n","  Attempting uninstall: zipp\n","    Found existing installation: zipp 3.8.1\n","    Uninstalling zipp-3.8.1:\n","      Successfully uninstalled zipp-3.8.1\n","  Attempting uninstall: typing-extensions\n","    Found existing installation: typing-extensions 4.1.1\n","    Uninstalling typing-extensions-4.1.1:\n","      Successfully uninstalled typing-extensions-4.1.1\n","  Attempting uninstall: six\n","    Found existing installation: six 1.15.0\n","    Uninstalling six-1.15.0:\n","      Successfully uninstalled six-1.15.0\n","  Attempting uninstall: numpy\n","    Found existing installation: numpy 1.21.6\n","    Uninstalling numpy-1.21.6:\n","      Successfully uninstalled numpy-1.21.6\n","  Attempting uninstall: MarkupSafe\n","    Found existing installation: MarkupSafe 2.0.1\n","    Uninstalling MarkupSafe-2.0.1:\n","      Successfully uninstalled MarkupSafe-2.0.1\n","  Attempting uninstall: importlib-metadata\n","    Found existing installation: importlib-metadata 5.0.0\n","    Uninstalling importlib-metadata-5.0.0:\n","      Successfully uninstalled importlib-metadata-5.0.0\n","  Attempting uninstall: wheel\n","    Found existing installation: wheel 0.37.1\n","    Uninstalling wheel-0.37.1:\n","      Successfully uninstalled wheel-0.37.1\n","  Attempting uninstall: werkzeug\n","    Found existing installation: Werkzeug 1.0.1\n","    Uninstalling Werkzeug-1.0.1:\n","      Successfully uninstalled Werkzeug-1.0.1\n","  Attempting uninstall: setuptools\n","    Found existing installation: setuptools 57.4.0\n","    Uninstalling setuptools-57.4.0:\n","      Successfully uninstalled setuptools-57.4.0\n","  Attempting uninstall: protobuf\n","    Found existing installation: protobuf 3.17.3\n","    Uninstalling protobuf-3.17.3:\n","      Successfully uninstalled protobuf-3.17.3\n","  Attempting uninstall: markdown\n","    Found existing installation: Markdown 3.4.1\n","    Uninstalling Markdown-3.4.1:\n","      Successfully uninstalled Markdown-3.4.1\n","  Attempting uninstall: h5py\n","    Found existing installation: h5py 3.1.0\n","    Uninstalling h5py-3.1.0:\n","      Successfully uninstalled h5py-3.1.0\n","  Attempting uninstall: grpcio\n","    Found existing installation: grpcio 1.49.1\n","    Uninstalling grpcio-1.49.1:\n","      Successfully uninstalled grpcio-1.49.1\n","  Attempting uninstall: absl-py\n","    Found existing installation: absl-py 1.2.0\n","    Uninstalling absl-py-1.2.0:\n","      Successfully uninstalled absl-py-1.2.0\n","  Attempting uninstall: wrapt\n","    Found existing installation: wrapt 1.14.1\n","    Uninstalling wrapt-1.14.1:\n","      Successfully uninstalled wrapt-1.14.1\n","  Attempting uninstall: termcolor\n","    Found existing installation: termcolor 2.0.1\n","    Uninstalling termcolor-2.0.1:\n","      Successfully uninstalled termcolor-2.0.1\n","  Attempting uninstall: tensorflow-estimator\n","    Found existing installation: tensorflow-estimator 2.8.0\n","    Uninstalling tensorflow-estimator-2.8.0:\n","      Successfully uninstalled tensorflow-estimator-2.8.0\n","  Attempting uninstall: tensorboard\n","    Found existing installation: tensorboard 2.8.0\n","    Uninstalling tensorboard-2.8.0:\n","      Successfully uninstalled tensorboard-2.8.0\n","  Attempting uninstall: opt-einsum\n","    Found existing installation: opt-einsum 3.3.0\n","    Uninstalling opt-einsum-3.3.0:\n","      Successfully uninstalled opt-einsum-3.3.0\n","  Attempting uninstall: keras-preprocessing\n","    Found existing installation: Keras-Preprocessing 1.1.2\n","    Uninstalling Keras-Preprocessing-1.1.2:\n","      Successfully uninstalled Keras-Preprocessing-1.1.2\n","  Attempting uninstall: google-pasta\n","    Found existing installation: google-pasta 0.2.0\n","    Uninstalling google-pasta-0.2.0:\n","      Successfully uninstalled google-pasta-0.2.0\n","  Attempting uninstall: gast\n","    Found existing installation: gast 0.5.3\n","    Uninstalling gast-0.5.3:\n","      Successfully uninstalled gast-0.5.3\n","  Attempting uninstall: astor\n","    Found existing installation: astor 0.8.1\n","    Uninstalling astor-0.8.1:\n","      Successfully uninstalled astor-0.8.1\n","  Attempting uninstall: tensorflow\n","    Found existing installation: tensorflow 2.8.2+zzzcolab20220929150707\n","    Uninstalling tensorflow-2.8.2+zzzcolab20220929150707:\n","      Successfully uninstalled tensorflow-2.8.2+zzzcolab20220929150707\n","\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n","ipython 7.9.0 requires jedi>=0.10, which is not installed.\n","xarray-einstats 0.2.2 requires numpy>=1.21, but you have numpy 1.18.5 which is incompatible.\n","thinc 8.1.2 requires typing-extensions<4.2.0,>=3.7.4.1; python_version < \"3.8\", but you have typing-extensions 4.4.0 which is incompatible.\n","tensorflow-probability 0.16.0 requires gast>=0.3.2, but you have gast 0.2.2 which is incompatible.\n","tensorflow-metadata 1.10.0 requires protobuf<4,>=3.13, but you have protobuf 4.21.7 which is incompatible.\n","tables 3.7.0 requires numpy>=1.19.0, but you have numpy 1.18.5 which is incompatible.\n","spacy 3.4.1 requires typing-extensions<4.2.0,>=3.7.4; python_version < \"3.8\", but you have typing-extensions 4.4.0 which is incompatible.\n","plotnine 0.8.0 requires numpy>=1.19.0, but you have numpy 1.18.5 which is incompatible.\n","numba 0.56.2 requires setuptools<60, but you have setuptools 65.4.1 which is incompatible.\n","kapre 0.3.7 requires tensorflow>=2.0.0, but you have tensorflow 1.15.5 which is incompatible.\n","jaxlib 0.3.20+cuda11.cudnn805 requires numpy>=1.20, but you have numpy 1.18.5 which is incompatible.\n","jax 0.3.21 requires numpy>=1.20, but you have numpy 1.18.5 which is incompatible.\n","google-cloud-bigquery-storage 1.1.2 requires protobuf<4.0.0dev, but you have protobuf 4.21.7 which is incompatible.\n","google-api-core 1.31.6 requires protobuf<4.0.0dev,>=3.12.0; python_version > \"3\", but you have protobuf 4.21.7 which is incompatible.\n","flask 1.1.4 requires Werkzeug<2.0,>=0.15, but you have werkzeug 2.2.2 which is incompatible.\n","cupy-cuda11x 11.0.0 requires numpy<1.26,>=1.20, but you have numpy 1.18.5 which is incompatible.\n","confection 0.0.2 requires typing-extensions<4.2.0,>=3.7.4.1; python_version < \"3.8\", but you have typing-extensions 4.4.0 which is incompatible.\n","cmdstanpy 1.0.7 requires numpy>=1.21, but you have numpy 1.18.5 which is incompatible.\u001b[0m\n","Successfully installed MarkupSafe-2.1.1 absl-py-1.2.0 astor-0.8.1 gast-0.2.2 google-pasta-0.2.0 grpcio-1.49.1 h5py-2.10.0 importlib-metadata-5.0.0 keras-applications-1.0.8 keras-preprocessing-1.1.2 markdown-3.4.1 numpy-1.18.5 opt-einsum-3.3.0 protobuf-4.21.7 setuptools-65.4.1 six-1.16.0 tensorboard-1.15.0 tensorflow-1.15.5 tensorflow-estimator-1.15.1 termcolor-2.0.1 typing-extensions-4.4.0 werkzeug-2.2.2 wheel-0.37.1 wrapt-1.14.1 zipp-3.9.0\n"]},{"output_type":"display_data","data":{"application/vnd.colab-display-data+json":{"pip_warning":{"packages":["astor","numpy","pkg_resources","six"]}}},"metadata":{}}]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/","height":1000},"id":"1iAkfFZbRet8","outputId":"ed0601ff-b783-4120-f9b7-d30bab0c0299"},"source":["!pip install py-agender"],"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/\n","Collecting py-agender\n","  Downloading py_agender-0.0.9-py3-none-any.whl (188.3 MB)\n","\u001b[K     |████████████████████████████████| 188.3 MB 19 kB/s \n","\u001b[?25hCollecting opencv-python<3.5,>=3.4.2+contrib\n","  Downloading opencv_python-3.4.18.65-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (58.4 MB)\n","\u001b[K     |████████████████████████████████| 58.4 MB 302 kB/s \n","\u001b[?25hCollecting Keras<2.2.5,>=2.2.4\n","  Downloading Keras-2.2.4-py2.py3-none-any.whl (312 kB)\n","\u001b[K     |████████████████████████████████| 312 kB 74.9 MB/s \n","\u001b[?25hCollecting twine>=1.10\n","  Downloading twine-4.0.1-py3-none-any.whl (36 kB)\n","Collecting numpy<=1.15.9,>=1.13\n","  Downloading numpy-1.15.4-cp37-cp37m-manylinux1_x86_64.whl (13.8 MB)\n","\u001b[K     |████████████████████████████████| 13.8 MB 51.7 MB/s \n","\u001b[?25hRequirement already satisfied: scipy>=0.14 in /usr/local/lib/python3.7/dist-packages (from Keras<2.2.5,>=2.2.4->py-agender) (1.7.3)\n","Requirement already satisfied: keras-applications>=1.0.6 in /usr/local/lib/python3.7/dist-packages (from Keras<2.2.5,>=2.2.4->py-agender) (1.0.8)\n","Requirement already satisfied: pyyaml in /usr/local/lib/python3.7/dist-packages (from Keras<2.2.5,>=2.2.4->py-agender) (6.0)\n","Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from Keras<2.2.5,>=2.2.4->py-agender) (1.16.0)\n","Requirement already satisfied: h5py in /usr/local/lib/python3.7/dist-packages (from Keras<2.2.5,>=2.2.4->py-agender) (2.10.0)\n","Requirement already satisfied: keras-preprocessing>=1.0.5 in /usr/local/lib/python3.7/dist-packages (from Keras<2.2.5,>=2.2.4->py-agender) (1.1.2)\n","Collecting scipy>=0.14\n","  Downloading scipy-1.7.2-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (38.2 MB)\n","\u001b[K     |████████████████████████████████| 38.2 MB 92.0 MB/s \n","\u001b[?25h  Downloading scipy-1.7.1-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (28.5 MB)\n","\u001b[K     |████████████████████████████████| 28.5 MB 1.2 MB/s \n","\u001b[?25h  Downloading scipy-1.7.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (28.5 MB)\n","\u001b[K     |████████████████████████████████| 28.5 MB 279 kB/s \n","\u001b[?25h  Downloading scipy-1.6.3-cp37-cp37m-manylinux1_x86_64.whl (27.4 MB)\n","\u001b[K     |████████████████████████████████| 27.4 MB 1.3 MB/s \n","\u001b[?25h  Downloading scipy-1.6.2-cp37-cp37m-manylinux1_x86_64.whl (27.4 MB)\n","\u001b[K     |████████████████████████████████| 27.4 MB 1.2 MB/s \n","\u001b[?25h  Downloading scipy-1.6.1-cp37-cp37m-manylinux1_x86_64.whl (27.4 MB)\n","\u001b[K     |████████████████████████████████| 27.4 MB 1.1 MB/s \n","\u001b[?25h  Downloading scipy-1.6.0-cp37-cp37m-manylinux1_x86_64.whl (27.4 MB)\n","\u001b[K     |████████████████████████████████| 27.4 MB 1.1 MB/s \n","\u001b[?25h  Downloading scipy-1.5.4-cp37-cp37m-manylinux1_x86_64.whl (25.9 MB)\n","\u001b[K     |████████████████████████████████| 25.9 MB 1.3 MB/s \n","\u001b[?25hCollecting rich>=12.0.0\n","  Downloading rich-12.6.0-py3-none-any.whl (237 kB)\n","\u001b[K     |████████████████████████████████| 237 kB 89.6 MB/s \n","\u001b[?25hCollecting requests-toolbelt!=0.9.0,>=0.8.0\n","  Downloading requests_toolbelt-0.10.0-py2.py3-none-any.whl (54 kB)\n","\u001b[K     |████████████████████████████████| 54 kB 3.4 MB/s \n","\u001b[?25hCollecting urllib3>=1.26.0\n","  Downloading urllib3-1.26.12-py2.py3-none-any.whl (140 kB)\n","\u001b[K     |████████████████████████████████| 140 kB 94.9 MB/s \n","\u001b[?25hCollecting readme-renderer>=35.0\n","  Downloading readme_renderer-37.2-py3-none-any.whl (14 kB)\n","Collecting rfc3986>=1.4.0\n","  Downloading rfc3986-2.0.0-py2.py3-none-any.whl (31 kB)\n","Requirement already satisfied: importlib-metadata>=3.6 in /usr/local/lib/python3.7/dist-packages (from twine>=1.10->py-agender) (5.0.0)\n","Collecting keyring>=15.1\n","  Downloading keyring-23.9.3-py3-none-any.whl (35 kB)\n","Collecting pkginfo>=1.8.1\n","  Downloading pkginfo-1.8.3-py2.py3-none-any.whl (26 kB)\n","Requirement already satisfied: requests>=2.20 in /usr/local/lib/python3.7/dist-packages (from twine>=1.10->py-agender) (2.23.0)\n","Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=3.6->twine>=1.10->py-agender) (3.9.0)\n","Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=3.6->twine>=1.10->py-agender) (4.4.0)\n","Collecting SecretStorage>=3.2\n","  Downloading SecretStorage-3.3.3-py3-none-any.whl (15 kB)\n","Collecting jaraco.classes\n","  Downloading jaraco.classes-3.2.3-py3-none-any.whl (6.0 kB)\n","Collecting jeepney>=0.4.2\n","  Downloading jeepney-0.8.0-py3-none-any.whl (48 kB)\n","\u001b[K     |████████████████████████████████| 48 kB 6.4 MB/s \n","\u001b[?25hRequirement already satisfied: Pygments>=2.5.1 in /usr/local/lib/python3.7/dist-packages (from readme-renderer>=35.0->twine>=1.10->py-agender) (2.6.1)\n","Requirement already satisfied: bleach>=2.1.0 in /usr/local/lib/python3.7/dist-packages (from readme-renderer>=35.0->twine>=1.10->py-agender) (5.0.1)\n","Requirement already satisfied: docutils>=0.13.1 in /usr/local/lib/python3.7/dist-packages (from readme-renderer>=35.0->twine>=1.10->py-agender) (0.17.1)\n","Requirement already satisfied: webencodings in /usr/local/lib/python3.7/dist-packages (from bleach>=2.1.0->readme-renderer>=35.0->twine>=1.10->py-agender) (0.5.1)\n","Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.20->twine>=1.10->py-agender) (2.10)\n","Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.20->twine>=1.10->py-agender) (3.0.4)\n","Collecting requests>=2.20\n","  Downloading requests-2.28.1-py3-none-any.whl (62 kB)\n","\u001b[K     |████████████████████████████████| 62 kB 1.2 MB/s \n","\u001b[?25hRequirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.20->twine>=1.10->py-agender) (2.1.1)\n","Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.20->twine>=1.10->py-agender) (2022.9.24)\n","Collecting commonmark<0.10.0,>=0.9.0\n","  Downloading commonmark-0.9.1-py2.py3-none-any.whl (51 kB)\n","\u001b[K     |████████████████████████████████| 51 kB 8.3 MB/s \n","\u001b[?25hCollecting cryptography>=2.0\n","  Downloading cryptography-38.0.1-cp36-abi3-manylinux_2_24_x86_64.whl (4.0 MB)\n","\u001b[K     |████████████████████████████████| 4.0 MB 78.9 MB/s \n","\u001b[?25hRequirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.7/dist-packages (from cryptography>=2.0->SecretStorage>=3.2->keyring>=15.1->twine>=1.10->py-agender) (1.15.1)\n","Requirement already satisfied: pycparser in /usr/local/lib/python3.7/dist-packages (from cffi>=1.12->cryptography>=2.0->SecretStorage>=3.2->keyring>=15.1->twine>=1.10->py-agender) (2.21)\n","Requirement already satisfied: more-itertools in /usr/local/lib/python3.7/dist-packages (from jaraco.classes->keyring>=15.1->twine>=1.10->py-agender) (8.14.0)\n","Installing collected packages: urllib3, numpy, jeepney, cryptography, SecretStorage, requests, jaraco.classes, commonmark, scipy, rich, rfc3986, requests-toolbelt, readme-renderer, pkginfo, keyring, twine, opencv-python, Keras, py-agender\n","  Attempting uninstall: urllib3\n","    Found existing installation: urllib3 1.24.3\n","    Uninstalling urllib3-1.24.3:\n","      Successfully uninstalled urllib3-1.24.3\n","  Attempting uninstall: numpy\n","    Found existing installation: numpy 1.18.5\n","    Uninstalling numpy-1.18.5:\n","      Successfully uninstalled numpy-1.18.5\n","  Attempting uninstall: requests\n","    Found existing installation: requests 2.23.0\n","    Uninstalling requests-2.23.0:\n","      Successfully uninstalled requests-2.23.0\n","  Attempting uninstall: scipy\n","    Found existing installation: scipy 1.7.3\n","    Uninstalling scipy-1.7.3:\n","      Successfully uninstalled scipy-1.7.3\n","  Attempting uninstall: opencv-python\n","    Found existing installation: opencv-python 4.6.0.66\n","    Uninstalling opencv-python-4.6.0.66:\n","      Successfully uninstalled opencv-python-4.6.0.66\n","  Attempting uninstall: Keras\n","    Found existing installation: keras 2.8.0\n","    Uninstalling keras-2.8.0:\n","      Successfully uninstalled keras-2.8.0\n","\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n","yellowbrick 1.5 requires numpy>=1.16.0, but you have numpy 1.15.4 which is incompatible.\n","xarray 0.20.2 requires numpy>=1.18, but you have numpy 1.15.4 which is incompatible.\n","xarray-einstats 0.2.2 requires numpy>=1.21, but you have numpy 1.15.4 which is incompatible.\n","thinc 8.1.2 requires typing-extensions<4.2.0,>=3.7.4.1; python_version < \"3.8\", but you have typing-extensions 4.4.0 which is incompatible.\n","tensorflow 1.15.5 requires numpy<1.19.0,>=1.16.0, but you have numpy 1.15.4 which is incompatible.\n","tensorflow-probability 0.16.0 requires gast>=0.3.2, but you have gast 0.2.2 which is incompatible.\n","tables 3.7.0 requires numpy>=1.19.0, but you have numpy 1.15.4 which is incompatible.\n","spacy 3.4.1 requires typing-extensions<4.2.0,>=3.7.4; python_version < \"3.8\", but you have typing-extensions 4.4.0 which is incompatible.\n","scikit-image 0.18.3 requires numpy>=1.16.5, but you have numpy 1.15.4 which is incompatible.\n","resampy 0.4.2 requires numpy>=1.17, but you have numpy 1.15.4 which is incompatible.\n","pywavelets 1.3.0 requires numpy>=1.17.3, but you have numpy 1.15.4 which is incompatible.\n","pyerfa 2.0.0.1 requires numpy>=1.17, but you have numpy 1.15.4 which is incompatible.\n","pyarrow 6.0.1 requires numpy>=1.16.6, but you have numpy 1.15.4 which is incompatible.\n","plotnine 0.8.0 requires numpy>=1.19.0, but you have numpy 1.15.4 which is incompatible.\n","pandas 1.3.5 requires numpy>=1.17.3; platform_machine != \"aarch64\" and platform_machine != \"arm64\" and python_version < \"3.10\", but you have numpy 1.15.4 which is incompatible.\n","numba 0.56.2 requires numpy<1.24,>=1.18, but you have numpy 1.15.4 which is incompatible.\n","numba 0.56.2 requires setuptools<60, but you have setuptools 65.4.1 which is incompatible.\n","kapre 0.3.7 requires numpy>=1.18.5, but you have numpy 1.15.4 which is incompatible.\n","kapre 0.3.7 requires tensorflow>=2.0.0, but you have tensorflow 1.15.5 which is incompatible.\n","jaxlib 0.3.20+cuda11.cudnn805 requires numpy>=1.20, but you have numpy 1.15.4 which is incompatible.\n","jax 0.3.21 requires numpy>=1.20, but you have numpy 1.15.4 which is incompatible.\n","httpstan 4.6.1 requires numpy<2.0,>=1.16, but you have numpy 1.15.4 which is incompatible.\n","gym 0.25.2 requires numpy>=1.18.0, but you have numpy 1.15.4 which is incompatible.\n","google-api-core 1.31.6 requires protobuf<4.0.0dev,>=3.12.0; python_version > \"3\", but you have protobuf 4.21.7 which is incompatible.\n","cupy-cuda11x 11.0.0 requires numpy<1.26,>=1.20, but you have numpy 1.15.4 which is incompatible.\n","cmdstanpy 1.0.7 requires numpy>=1.21, but you have numpy 1.15.4 which is incompatible.\n","astropy 4.3.1 requires numpy>=1.17, but you have numpy 1.15.4 which is incompatible.\n","aesara 2.7.9 requires numpy>=1.17.0, but you have numpy 1.15.4 which is incompatible.\n","aeppl 0.0.33 requires numpy>=1.18.1, but you have numpy 1.15.4 which is incompatible.\u001b[0m\n","Successfully installed Keras-2.2.4 SecretStorage-3.3.3 commonmark-0.9.1 cryptography-38.0.1 jaraco.classes-3.2.3 jeepney-0.8.0 keyring-23.9.3 numpy-1.15.4 opencv-python-3.4.18.65 pkginfo-1.8.3 py-agender-0.0.9 readme-renderer-37.2 requests-2.28.1 requests-toolbelt-0.10.0 rfc3986-2.0.0 rich-12.6.0 scipy-1.5.4 twine-4.0.1 urllib3-1.26.12\n"]},{"output_type":"display_data","data":{"application/vnd.colab-display-data+json":{"pip_warning":{"packages":["numpy"]}}},"metadata":{}}]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/","height":1000},"id":"5yZZXURJRdci","outputId":"2a446a74-a39a-4483-8528-6843774561aa"},"source":["from pyagender import PyAgender"],"execution_count":null,"outputs":[{"output_type":"stream","name":"stderr","text":["Using TensorFlow backend.\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"output_type":"stream","name":"stdout","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py\", line 3326, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-3-f536ed1c9483>\", line 1, in <module>\n","    from pyagender import PyAgender\n","  File \"/usr/local/lib/python3.7/dist-packages/pyagender/__init__.py\", line 1, in <module>\n","    from pyagender.pyagender import *\n","  File \"/usr/local/lib/python3.7/dist-packages/pyagender/pyagender.py\", line 10, in <module>\n","    from pyagender.wide_resnet import WideResNet\n","  File \"/usr/local/lib/python3.7/dist-packages/pyagender/wide_resnet.py\", line 4, in <module>\n","    from keras.models import Model\n","  File \"/usr/local/lib/python3.7/dist-packages/keras/__init__.py\", line 3, in <module>\n","    from . import utils\n","  File \"/usr/local/lib/python3.7/dist-packages/keras/utils/__init__.py\", line 6, in <module>\n","    from . import conv_utils\n","  File \"/usr/local/lib/python3.7/dist-packages/keras/utils/conv_utils.py\", line 9, in <module>\n","    from .. import backend as K\n","  File \"/usr/local/lib/python3.7/dist-packages/keras/backend/__init__.py\", line 89, in <module>\n","    from .tensorflow_backend import *\n","  File \"/usr/local/lib/python3.7/dist-packages/keras/backend/tensorflow_backend.py\", line 5, in <module>\n","    import tensorflow as tf\n","  File \"/usr/local/lib/python3.7/dist-packages/tensorflow/__init__.py\", line 102, in <module>\n","    from tensorflow_core import *\n","  File \"/usr/local/lib/python3.7/dist-packages/tensorflow_core/__init__.py\", line 28, in <module>\n","    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import\n","  File \"<frozen importlib._bootstrap>\", line 1019, in _handle_fromlist\n","  File \"/usr/local/lib/python3.7/dist-packages/tensorflow/__init__.py\", line 50, in __getattr__\n","    module = self._load()\n","  File \"/usr/local/lib/python3.7/dist-packages/tensorflow/__init__.py\", line 44, in _load\n","    module = _importlib.import_module(self.__name__)\n","  File \"/usr/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n","    return _bootstrap._gcd_import(name[level:], package, level)\n","  File \"/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/__init__.py\", line 52, in <module>\n","    from tensorflow.core.framework.graph_pb2 import *\n","  File \"/usr/local/lib/python3.7/dist-packages/tensorflow_core/core/framework/graph_pb2.py\", line 16, in <module>\n","    from tensorflow.core.framework import node_def_pb2 as tensorflow_dot_core_dot_framework_dot_node__def__pb2\n","  File \"/usr/local/lib/python3.7/dist-packages/tensorflow_core/core/framework/node_def_pb2.py\", line 16, in <module>\n","    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2\n","  File \"/usr/local/lib/python3.7/dist-packages/tensorflow_core/core/framework/attr_value_pb2.py\", line 16, in <module>\n","    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2\n","  File \"/usr/local/lib/python3.7/dist-packages/tensorflow_core/core/framework/tensor_pb2.py\", line 16, in <module>\n","    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2\n","  File \"/usr/local/lib/python3.7/dist-packages/tensorflow_core/core/framework/resource_handle_pb2.py\", line 16, in <module>\n","    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2\n","  File \"/usr/local/lib/python3.7/dist-packages/tensorflow_core/core/framework/tensor_shape_pb2.py\", line 42, in <module>\n","    serialized_options=None, file=DESCRIPTOR),\n","  File \"/usr/local/lib/python3.7/dist-packages/google/protobuf/descriptor.py\", line 560, in __new__\n","    _message.Message._CheckCalledFromGeneratedFile()\n","TypeError: Descriptors cannot not be created directly.\n","If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.\n","If you cannot immediately regenerate your protos, some other possible workarounds are:\n"," 1. Downgrade the protobuf package to 3.20.x or lower.\n"," 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).\n","\n","More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py\", line 2040, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/core/ultratb.py\", line 319, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/core/ultratb.py\", line 353, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.7/inspect.py\", line 696, in getsourcefile\n","    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n","  File \"/usr/lib/python3.7/inspect.py\", line 733, in getmodule\n","    if ismodule(module) and hasattr(module, '__file__'):\n","  File \"/usr/local/lib/python3.7/dist-packages/tensorflow/__init__.py\", line 50, in __getattr__\n","    module = self._load()\n","  File \"/usr/local/lib/python3.7/dist-packages/tensorflow/__init__.py\", line 44, in _load\n","    module = _importlib.import_module(self.__name__)\n","  File \"/usr/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n","    return _bootstrap._gcd_import(name[level:], package, level)\n","  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n","  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n","  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n","  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n","  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n","  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n","  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n","  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n","  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n","  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n","  File \"/usr/local/lib/python3.7/dist-packages/tensorflow_core/__init__.py\", line 33, in <module>\n","    from tensorflow._api.v1 import audio\n","  File \"/usr/local/lib/python3.7/dist-packages/tensorflow_core/_api/v1/audio/__init__.py\", line 10, in <module>\n","    from tensorflow.python.ops.gen_audio_ops import decode_wav\n","  File \"/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/ops/gen_audio_ops.py\", line 11, in <module>\n","    from tensorflow.python.eager import context as _context\n","  File \"/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/eager/context.py\", line 29, in <module>\n","    from tensorflow.core.protobuf import config_pb2\n","  File \"/usr/local/lib/python3.7/dist-packages/tensorflow_core/core/protobuf/config_pb2.py\", line 16, in <module>\n","    from tensorflow.core.framework import cost_graph_pb2 as tensorflow_dot_core_dot_framework_dot_cost__graph__pb2\n","  File \"/usr/local/lib/python3.7/dist-packages/tensorflow_core/core/framework/cost_graph_pb2.py\", line 16, in <module>\n","    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2\n","  File \"/usr/local/lib/python3.7/dist-packages/tensorflow_core/core/framework/tensor_shape_pb2.py\", line 42, in <module>\n","    serialized_options=None, file=DESCRIPTOR),\n","  File \"/usr/local/lib/python3.7/dist-packages/google/protobuf/descriptor.py\", line 560, in __new__\n","    _message.Message._CheckCalledFromGeneratedFile()\n","TypeError: Descriptors cannot not be created directly.\n","If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.\n","If you cannot immediately regenerate your protos, some other possible workarounds are:\n"," 1. Downgrade the protobuf package to 3.20.x or lower.\n"," 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).\n","\n","More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates\n"]},{"output_type":"error","ename":"TypeError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m"]}]},{"cell_type":"markdown","metadata":{"id":"NvfVgReG_cOJ"},"source":["## Testing images"]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"fvBkR_N9_kZ3","outputId":"7099a267-0c12-4001-8c88-c2d3763ae3f8"},"source":["!wget https://www.dropbox.com/s/2747g2z7c4rb8ii/facesABC.zip\n","!unzip facesABC.zip"],"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["--2022-10-11 16:31:40--  https://www.dropbox.com/s/2747g2z7c4rb8ii/facesABC.zip\n","Resolving www.dropbox.com (www.dropbox.com)... 162.125.65.18, 2620:100:6021:18::a27d:4112\n","Connecting to www.dropbox.com (www.dropbox.com)|162.125.65.18|:443... connected.\n","HTTP request sent, awaiting response... 302 Found\n","Location: /s/raw/2747g2z7c4rb8ii/facesABC.zip [following]\n","--2022-10-11 16:31:40--  https://www.dropbox.com/s/raw/2747g2z7c4rb8ii/facesABC.zip\n","Reusing existing connection to www.dropbox.com:443.\n","HTTP request sent, awaiting response... 302 Found\n","Location: https://uca86c31bcd50c1190e15a8299a8.dl.dropboxusercontent.com/cd/0/inline/BurypyRWRidBaGXqucjCV2mFkz2IcAJGSKyasWeL5ac4HFRNei9uG_eIdkSFPR2ZOp3rBsOavckpzEGn6ioujwNfsAG4k7VKXvy5wNZvRYeD2bn_3kKqEddH4AXZOZZd4Ub4Hh-r6NC3hMm_TPXCOISXgFHnDNJD6RFMkOCOwdf22A/file# [following]\n","--2022-10-11 16:31:41--  https://uca86c31bcd50c1190e15a8299a8.dl.dropboxusercontent.com/cd/0/inline/BurypyRWRidBaGXqucjCV2mFkz2IcAJGSKyasWeL5ac4HFRNei9uG_eIdkSFPR2ZOp3rBsOavckpzEGn6ioujwNfsAG4k7VKXvy5wNZvRYeD2bn_3kKqEddH4AXZOZZd4Ub4Hh-r6NC3hMm_TPXCOISXgFHnDNJD6RFMkOCOwdf22A/file\n","Resolving uca86c31bcd50c1190e15a8299a8.dl.dropboxusercontent.com (uca86c31bcd50c1190e15a8299a8.dl.dropboxusercontent.com)... 162.125.65.15, 2620:100:6027:15::a27d:480f\n","Connecting to uca86c31bcd50c1190e15a8299a8.dl.dropboxusercontent.com (uca86c31bcd50c1190e15a8299a8.dl.dropboxusercontent.com)|162.125.65.15|:443... connected.\n","HTTP request sent, awaiting response... 302 Found\n","Location: /cd/0/inline2/BuocXd9u8lnzVWh6BUaJMSXAu5y7eZnR6kKbr_mXg4I1b97gNA7dh22esQRlhXNZGIJA-EeKRYDV7q4hjj6rin2QVYA0I47TZKC8ZcqIOzHyUpJ5gUrsTCppcAM7285BdBKTZOSZAUYLEKo7Pyzaq2UsrUfTC1suDNuAeSUWN11CCScNxPSUDJVmBYJzbm16Rxddeo5HEvOpyyOU62D1beFBF5HH0--QNiPy1tH-zn9pGVY2afzVpsrc4LlXBxqKZ0f7W6-kkx8R1vD8UmuJrIbU8Tln1burMZoET1W2Ul_RA6xl7u6LMxvRwKn_RnDJAaGxmnyabsAxSh3JocLQPqcWmiFKx8HBRUsa1Vb2FiLcDJqTYUfljQ1e0XL-q4q4TPrStL8LsercOnOSJYj6K9gO3esjoKOt_KkLoo-SxhYz_A/file [following]\n","--2022-10-11 16:31:41--  https://uca86c31bcd50c1190e15a8299a8.dl.dropboxusercontent.com/cd/0/inline2/BuocXd9u8lnzVWh6BUaJMSXAu5y7eZnR6kKbr_mXg4I1b97gNA7dh22esQRlhXNZGIJA-EeKRYDV7q4hjj6rin2QVYA0I47TZKC8ZcqIOzHyUpJ5gUrsTCppcAM7285BdBKTZOSZAUYLEKo7Pyzaq2UsrUfTC1suDNuAeSUWN11CCScNxPSUDJVmBYJzbm16Rxddeo5HEvOpyyOU62D1beFBF5HH0--QNiPy1tH-zn9pGVY2afzVpsrc4LlXBxqKZ0f7W6-kkx8R1vD8UmuJrIbU8Tln1burMZoET1W2Ul_RA6xl7u6LMxvRwKn_RnDJAaGxmnyabsAxSh3JocLQPqcWmiFKx8HBRUsa1Vb2FiLcDJqTYUfljQ1e0XL-q4q4TPrStL8LsercOnOSJYj6K9gO3esjoKOt_KkLoo-SxhYz_A/file\n","Reusing existing connection to uca86c31bcd50c1190e15a8299a8.dl.dropboxusercontent.com:443.\n","HTTP request sent, awaiting response... 200 OK\n","Length: 1170524 (1.1M) [application/zip]\n","Saving to: ‘facesABC.zip’\n","\n","facesABC.zip        100%[===================>]   1.12M  --.-KB/s    in 0.09s   \n","\n","2022-10-11 16:31:41 (12.6 MB/s) - ‘facesABC.zip’ saved [1170524/1170524]\n","\n","Archive:  facesABC.zip\n","  inflating: faceB.png               \n","  inflating: __MACOSX/._faceB.png    \n","  inflating: faceA.png               \n","  inflating: __MACOSX/._faceA.png    \n","  inflating: faceC.jpg               \n","  inflating: __MACOSX/._faceC.jpg    \n"]}]},{"cell_type":"code","metadata":{"id":"RLOZ-NgoS9kZ"},"source":["import cv2\n","import matplotlib.pyplot as plt\n","\n","\n","A = cv2.imread('faceA.png')\n","B = cv2.imread('faceB.png')\n","C = cv2.imread('faceC.jpg')\n","\n","plt.imshow(cv2.cvtColor(A, cv2.COLOR_BGR2RGB))\n","plt.title('A')\n","plt.show()\n","plt.imshow(cv2.cvtColor(B, cv2.COLOR_BGR2RGB))\n","plt.title('B')\n","plt.show()\n","plt.imshow(cv2.cvtColor(C, cv2.COLOR_BGR2RGB))\n","plt.title('C')\n","plt.show()\n"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"BjEf5IB7AB6n"},"source":["## Age and Gender"]},{"cell_type":"code","metadata":{"id":"efRt4IJqW2ot"},"source":["agender = PyAgender()"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"kGWncLmaSrwA"},"source":["X = B # input image\n","faces = agender.detect_genders_ages(X)\n","\n","gender_age = agender.gender_age(X)\n","gender = gender_age[0]>0.5\n","age    = round(gender_age[1])\n","\n","plt.imshow(cv2.cvtColor(X, cv2.COLOR_BGR2RGB))\n","plt.show()\n","\n","\n","if gender:\n","  print('Woman: '+str(age)+' years old')\n","else:\n","  print('Man: '+str(age)+' years old')\n"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"NlFtKQEUAMBW"},"source":["X = C # input image\n","faces = agender.detect_genders_ages(X)\n","\n","gender_age = agender.gender_age(X)\n","gender = gender_age[0]>0.5\n","age    = round(gender_age[1])\n","\n","plt.imshow(cv2.cvtColor(X, cv2.COLOR_BGR2RGB))\n","plt.show()\n","\n","\n","if gender:\n","  print('Woman: '+str(age)+' years old')\n","else:\n","  print('Man: '+str(age)+' years old')\n"],"execution_count":null,"outputs":[]}]}